# Generated by Django 4.1.3 on 2022-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
