# Generated by Django 4.1.3 on 2022-11-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
